# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a02d84c1b1f8d38cbaf89e7d53bd895c9ceacf45c1abb8e0f9545936e20ce7765b8efb769f7657c702c86013b3278f1077faebe46e09b2c1389d468df55ad6a2

test:
  secret_key_base: c32a6afb04a09b5c57b459856c993fac602fc9c7b3a0cf6bf50112c38c79a395f649b5ea1d8a5174c9a86b3fab9f4a9ef3dadaf6d769144e48babf02a89da6a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
